### ISSUE TITLE
Firmware 004.05 makes LED flash, OwlNest can't connect

### ISSUE THREAD

**Issue by tapirbait** [pingdynasty/OwlWare#12]
Hi,

After flashing Firmware 004.05 onto my Pedal with OwlNest, I rebooted by disconnecting USB and reconnecting again. After booting, the LED flashed in red and green but OwlNest could not really connect. It was that I tried to get the device information, which worked fine before. Now it did not work anymore.  
I had to go to DFU mode by holding the button when powering on, in order to flash the older firmware 004.04. That one worked fine again. I could get the device information in OwlNest. It showed proper firmware version.  
Now how can I make the new firmware rev.004.05 work?

Regards, tapirbait

**Comment by tapirbait** [comment]
Hi, the day after I wrote this issue, i had some sentences to clarify my point:
I was confused when I connected the freshly updated (rev004.05) pedal to my pc and the led flashed green and red and i could not use it.  
Note that I'm on win7 64bit with latest winusb driver installed with the suggested tool and latest OwlNest as of 2/2015.  
My more specific question is: what does the led flashing in green and red tell. Is this intended? Do I just have to push/click something to initialize the pedal?  
Have there been any changes to the usb communication since rev004.04? I have an AMD processor which implies there is a different USB controller than on intel platforms. I had some issues in the past with a specific other USB device that were only happening with this controller and device.

**Comment by marsus** [comment]
hallo -
are you using the latest OwlNest release [1]? 
Did you download the firmware using the OwlNest?

[1] https://github.com/pingdynasty/OwlNest/releases

**Comment by marsus** [comment]
Some users have reported problems with MIDI and DFU drivers on windows. The solution that seems to work best is to use Zadig to remove/reinstall the drivers when things go wrong.

pls have a look in the forum:
http://hoxtonowl.com/forums/search/zadig/

The OWL flashes red three times when you invoke the bootloader. Apart from that, the LED usually indicates which patch is active, red or green - or none, in bypass mode. Pressing the button should generally toggle the LED between red and green.

**Comment by tapirbait** [comment]
Hi, i just noticed we wrote nearly the same moment. Concerning your questions: yes, i did use the latest owlnest and used that one to load the latest Firmware. I downloaded it all the day i opened this issue.  
I also tried loading rev.004.05 'by hand', the results were the same.

**Comment by tapirbait** [comment]
Hm concerning zadiq, i'm sceptic if that is the problem. I installed the latest zadiq and winusb driver the day i opened this issue. And what makes up the doubt is that rev004.04 works fine with the same driver.

**Comment by tapirbait** [comment]
Btw, the dfu mode to be entered by holding the button when connecting usb worked with both firmware versions, r004.04 and r004.05.  
I will try updating the drivers with zadiq, the next time i play with the owl. I then can tell if it worked.

**Comment by marsus** [comment]
Yes I saw your comment pop as I was writing mine!

I think you're right about the drivers - if 04 works then 05 should work as well.

Is it possible the file is corrupted?
Pls try downloading Rev004.05 from here: https://github.com/pingdynasty/OwlWare/releases

**Comment by tapirbait** [comment]
Marsus, thanks for your suggestions. I'll try them the next time i have time. Right now i'm writing from my tablet. Just one question: i hope its not a problem, that i still have the stock bootloader. I never updated it, as i first want to get the Owlware package running on win7-64, in order to issue the right `make` commands to update the bootloader.

**Comment by marsus** [comment]
Keep the bootloader: if it ain't broken, don't fix it!

**Comment by pingdynasty** [comment]
fixed
