### ISSUE TITLE
Define factory patch set

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlWare#14]
We need a cut-down list of quality patches that we want to be included in a factory patch list.
A representative selection of 32 good, useful patches should be enough.

**Comment by pingdynasty** [comment]
Let me start the list:
- DroneBox
- FreeVerb
- Phaser
- Faust/SmoothDelay
- Filtered Delay
- Moog Drive Filter
- Parametric EQ
- Four Band EQ
- MDA/Bandisto
- Guitarix/BigMuffFuzz
- Overdrive
- Faust/StereoWah

**Comment by tamagazzi** [comment]
I would add these, too:

Simple Delay
Simple Distortion
Faust/Harp
Faust/Pitch Shifter
Guitarix/Dunwah
Guitarix/Moog Filter
Guitarix/Phasor
Contest/Dual Tremolo
OL/Dual Pitch Shifter
OL/Wierd Phaser
Jot Reverb
Plate Verb

and also Charles Verron's Siren patch, although it's not in the current firmware

**Comment by GuillaumeLeNost** [comment]
Also, we made the Mood Drive stereo with Silvere.
I need to add it to the fw.

Otherwise the selection is good !

**Comment by pingdynasty** [comment]
done
