### ISSUE TITLE
Expression pedal assignement

### ISSUE THREAD

**Issue by GuillaumeLeNost** [pingdynasty/OwlWare#17]
Suggestion from Conik the sax player:
it would be nice to be able to select the expression pedal assignment.

Following the same logic for bank/preset selection:
- when holding down the LED
- turning knob C would assign Expression pedal to Parameter A, B, C, or D.

**Comment by pingdynasty** [comment]
Great suggestions.
Would have to add some logic so that you don't accidentally change patch when you want to change expression assignment and vice versa.
