### ISSUE TITLE
Control LED from patch

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlWare#22]
The patch program should be able to control the colour of the LED without changing the output gate.
This should be done through `setButton()` in the API (with `GREEN_BUTTON` and `RED_BUTTON` button IDs) and suitable message hooks for Pd.

Ref: https://hoxtonowl.com/forums/topic/pd-s-channel-push-not-working/

**Comment by jayrope** [comment]
Did this already make it into V12? And does it work with Gen, too? How? Thank you!

**Comment by jayrope** [comment]
Your own suggestion: Set up an additional audio stream for this. I'd say a samplerate of 1 or 2KHz would probably be good enough for just the display. Maybe that's technically possible to save on CPU (?).
