### ISSUE TITLE
Owl Pedal Website Down?

### ISSUE THREAD

**Issue by jeffreypierce** [pingdynasty/OwlWare#29]
It seems the https://hoxtonowl.com/ linked in the main markdown file is no longer live and the domain is for sale. Is this expected?

<img width="1559" alt="Screen Shot 2021-09-25 at 9 43 36 AM" src="https://user-images.githubusercontent.com/280740/134773736-ad35f460-f13f-4f70-955d-e62fc6f3df5e.png">

**Comment by Hieronymu5** [comment]
https://community.rebeltech.org

**Comment by jeffreypierce** [comment]
Thanks!

**Comment by pingdynasty** [comment]
thanks both!
I've updated the readme with links to the new website and firmware repo.
